## APPLY THE KRILLIN PATCHES FOR A WORKING BUILD ##
##    THANKS TO KRA105 FOR THE BASE SCRIPTS      ##
## AND ALL THE PEOPLE THAT HELP WITH THIS PATCHES##

sh device/bq/krillin/patches-krillin/apply.sh
